Proof the library works with Alamofire
net-a-porter-mobile/NSURLSession-Mock pull request #38
Opened 2017-04-20 18:56 UTC by nap-sam-dean

2017-04-20 18:58 UTC, nap-sam-dean commented
This should fix #6

2017-04-25 20:31 UTC, kerrmarin commented
I'll review this tonight 👍

2017-04-27 02:57 UTC, kerrmarin requested changes
Looks awesome 💯  just the one comment on the `tearDown` method and we're good to go 👍

2017-04-27 02:57 UTC, kerrmarin commented on Example/Tests/AlamofireTests.swift
> +//  Copyright © 2016 CocoaPods. All rights reserved.
Trivial, but should the Copyright read something else instead of CocoaPods?

2017-04-27 02:57 UTC, kerrmarin commented on Example/Tests/AlamofireTests.swift
> +        URLSession.removeAllMocks()
Missing call to `super`?

2017-04-27 08:32 UTC, nap-sam-dean commented on Example/Tests/AlamofireTests.swift
> +//  Copyright © 2016 CocoaPods. All rights reserved.
Hah - not only here :) Fixed.

2017-04-27 08:32 UTC, nap-sam-dean commented on Example/Tests/AlamofireTests.swift
> +        URLSession.removeAllMocks()
Yep - fixed.

2017-04-27 17:29 UTC, kerrmarin approved these changes

2017-04-27 20:13 UTC, merged